---

- name: appends java agent to setenv.sh
  lineinfile:
    dest="/opt/{{ tomcat_version }}/bin/setenv.sh"
    line='export JAVA_OPTS="$JAVA_OPTS -javaagent:{{newrelic_installation_dir}}/newrelic/newrelic.jar"'
    owner=tomcat
    group=tomcat
    state=present
    mode=0770
    insertafter=EOF
    create=true